### ISSUE TITLE
Bug: pass []any as any in variadic function

### ISSUE THREAD

**Issue by alingse** [syke99/dynaQ#5] opened 2022-07-11 14:42 UTC
i am writing a [linter](https://github.com/alingse/asasalint) to lint that pass []any as any in variadic function

and run github Actions for some top go packages, this package failed

see github actions lint result here https://github.com/alingse/asasalint/runs/7284512845?check_suite_focus=true

```
Error: /home/runner/work/asasalint/asasalint/dynaQ/dq.go:99:60: pass []any as any to func Query func(dBase *database/sql.DB, query string, timeFormat string, queryParams ...interface{}) ([][]github.com/syke99/dynaQ/pkg/resources/models.QueryValue, error)
Error: /home/runner/work/asasalint/asasalint/dynaQ/dq.go:115:63: pass []any as any to func QueryRow func(dBase *database/sql.DB, query string, timeFormat string, queryParams ...interface{}) ([]github.com/syke99/dynaQ/pkg/resources/models.QueryValue, error)
Error: /home/runner/work/asasalint/asasalint/dynaQ/dq.go:132:[7](https://github.com/alingse/asasalint/runs/7284512845?check_suite_focus=true#step:7:8)6: pass []any as any to func QueryWithContext func(dBase *database/sql.DB, ctx context.Context, query string, timeFormat string, queryParams ...interface{}) ([][]github.com/syke99/dynaQ/pkg/resources/models.QueryValue, error)
```

**Comment by syke99** [comment] 2022-07-11 15:18
Hey, thanks for testing out dynaQ!! I think I know what the issue is and I'll work on it ASAP!! If you would like to fix this issue and to submit a PR, please fork this repo and then create a PR whenever it's complete, and if accepted, I'll merge it in!! (Also, this reminds me I need to set up a code of conduct for contributing, so thanks for that reminder as well!!)

**Comment by syke99** [comment] 2022-07-11 16:21
Hey @alingse, I already went ahead and tried to fix this issue. Would you might testing the branch `issue5` to test my fix?

**Comment by alingse** [comment] 2022-07-11 16:24
sorry, my github action work on the default branch 😂  it's not configurable.

you can try install the [linter](https://github.com/alingse/asasalint)  on local with `go install github.com/alingse/asasalint/cmd/asasalint@latest`

i am working on add the linter into golangci-lint, maybe that will be easy to check.

**Comment by syke99** [comment] 2022-07-11 16:29
Haha okay, no worries!! Thanks for letting me know. I'll give it a shot (and thanks for the linter tool!! Seems like a really cool idea 😜)

**Comment by syke99** [comment] 2022-07-11 16:30
I gave it a shot and didn't get any messages back. I assume this means it passed? @alingse

**Comment by alingse** [comment] 2022-07-11 16:39
yes, no message is means that passed. 🌮

**Comment by syke99** [comment] 2022-07-11 16:40
Perfect, thanks!! I'll get it merged in. And thanks again for checking out dynaQ!!

**Closed as completed by syke99** 2022-07-11 16:40 UTC
